### ISSUE TITLE
vue-cli下直接报‘JRoll is not defined(…)’

### ISSUE THREAD

**Issue by ghost** [chjtx/JRoll-Vue-Infinite#1]
import JRoll from 'jroll-vue-infinite'

export default {
    components: {
      'jroll-infinite': JRoll.VueInfinite()
    }
｝

**Comment by chjtx** [comment]
@hee93 `jroll-vue-infinite`是JRoll的一个扩展，必须依赖JRoll，所以要先引入JRoll

```js
import JRoll from 'jroll'
import 'jroll-vue-infinite'
```
